# Qarvix Swaylock Theme
color=1a1b26
inside-color=1a1b26cc
ring-color=7aa2f7
key-hl-color=7dcfff
line-color=00000000
separator-color=00000000
inside-clear-color=e0af68cc
ring-clear-color=e0af68
inside-ver-color=7aa2f7cc
ring-ver-color=7aa2f7
inside-wrong-color=f7768ecc
ring-wrong-color=f7768e
bs-hl-color=f7768e
text-color=c0caf5
text-clear-color=1a1b26
text-ver-color=1a1b26
text-wrong-color=1a1b26
font=Fira Code
font-size=16
indicator-radius=80
indicator-thickness=8
